% @Knoblesse 2022
% Select Tank to open, and gather draw figure
% Path : string path to the tank

Path = 'D:\Data_fib\fpm220920\ToneFib-220920-125614_fpm16_ext';
extinction_trials_per_graph = 6;
draw_ribbon_result = false;
us_offset = 2.5;
 
%% Load Data 
Data = loadFibData(Path, 'verbose', true);
exp_type = autoDetectExpType(Data.path);

%% Parse Exp Data
exp_info = regexp(Data.path, '.*\.*-(?<exp_date>\d{6})-\d{6}_(?<exp_subject>.*)_.*', 'names');

if isempty(exp_info)
    warning('Can not parse the Tank name.');
    exp_info(1).exp_subject = 'Unknown Subject';
    exp_info(1).exp_date = '??/??';
else
    fprintf('Experiment info parsed from the Tank name.\n');
    fprintf('       └Subject : %s\n', exp_info.exp_subject);
    fprintf('       └Date : %s\n', exp_info.exp_date);
end

%% Process Data
Data = processFibData(Data,...
    'verbose', false,...
    'timewindow', [-5, 20],...
    'baseline_correction', "z",...
    'baseline_mode', "mix",...
    'baseline_trial_duration', 1,...
    'baseline_trial_ignore_duration', 0,...
    'baseline_whole_duration', 60,...
    'baseline_whole_ignore_duration', 60,...
    'baseline_mix_duration', [1, 60],...
    'baseline_mix_ignore_duration', [0, 60],...
    'filter', 0.5,...
    'detrend', true,...
    'initial_artifact_remove_time', 30);

%% Plot Data
drawdFF(Data, exp_type, extinction_trials_per_graph, us_offset,...
    'figureName', sprintf("%s : %s - %s", exp_type, exp_info.exp_subject, exp_info.exp_date),...
    'draw_total_result', true);
