
%% Create a figure for ribbon plot
if draw_ribbon_result == false
    return
end
figure(...
    'Name', sprintf("Ribbon %s : %s - %s", exp_type, exp_info.exp_subject, exp_info.exp_date),...
    'Position', [180, 340, 1300, 500]);
axis = subplot(1,1,1);
hold on;
axis.View = [ 66.5195   42.8032];

%% Prepare Dataset

windowStartIndex = round(options.timewindow(1) * Data.fs);
windowEndIndex = windowStartIndex + windowIndexLength - 1;
windowInSeconds = [windowStartIndex, windowEndIndex] ./ Data.fs;

ribbons = ribbon(linspace(windowInSeconds(1), windowInSeconds(2), windowIndexLength), data2plot);
cdata = jet(numSubFigure);
for subfigure = 1 : numSubFigure
    ribbons(subfigure).LineStyle = 'none';
    ribbons(subfigure).FaceColor = cdata(subfigure,:);
end

axis_x = xlim();
axis_y = ylim();
axis_z = zlim();
grid on;
xlabel('Trials');
ylabel('Time(s)');
zlabel('\Delta');
axis.XTickLabel{1} = "";
axis.XTickLabel{end} = "";

% Draw CS US Area
cs_times = [0, diff(Data.cs(1,:))]; % beware. only CS duration from the first trial is used.
fill3(...
    [axis_x(1), axis_x(1), axis_x(1), axis_x(1)],...
    [cs_times(1), cs_times(2), cs_times(2), cs_times(1)],...
    [axis_z(1), axis_z(1), axis_z(2), axis_z(2)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
    'EdgeAlpha', 0.1);
fill3(...
    [axis_x(2), axis_x(2), axis_x(2), axis_x(2)],...
    [cs_times(1), cs_times(2), cs_times(2), cs_times(1)],...
    [axis_z(1), axis_z(1), axis_z(2), axis_z(2)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
    'EdgeAlpha', 0.1);
fill3(...
    [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
    [cs_times(1), cs_times(2), cs_times(2), cs_times(1)],...
    [axis_z(2), axis_z(2), axis_z(2), axis_z(2)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
    'EdgeAlpha', 0.1);
fill3(...
    [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
    [cs_times(1), cs_times(2), cs_times(2), cs_times(1)],...
    [axis_z(1), axis_z(1), axis_z(1), axis_z(1)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
   	'EdgeAlpha', 0.1);
fill3(...
    [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
    [cs_times(1), cs_times(1), cs_times(1), cs_times(1)],...
    [axis_z(1), axis_z(2), axis_z(2), axis_z(1)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
    'EdgeAlpha', 0.1);
fill3(...
    [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
    [cs_times(2), cs_times(2), cs_times(2), cs_times(2)],...
    [axis_z(1), axis_z(2), axis_z(2), axis_z(1)],...
    [69, 184, 220] ./ 255,...
    'FaceAlpha', 0.1,...
    'LineStyle', '-',...
    'EdgeAlpha', 0.1);

if exp_type == "Conditioning"
    us_color = [1, 0, 0];
    fill3(...
        [axis_x(1), axis_x(1), axis_x(1), axis_x(1)],...
        [cs_times(2) - options.us_offset, cs_times(2), cs_times(2), cs_times(2) - options.us_offset],...
        [axis_z(1), axis_z(1), axis_z(2), axis_z(2)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
        'EdgeAlpha', 0.1);
    fill3(...
        [axis_x(2), axis_x(2), axis_x(2), axis_x(2)],...
        [cs_times(2) - options.us_offset, cs_times(2), cs_times(2), cs_times(2) - options.us_offset],...
        [axis_z(1), axis_z(1), axis_z(2), axis_z(2)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
        'EdgeAlpha', 0.1);
    fill3(...
        [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
        [cs_times(2) - options.us_offset, cs_times(2), cs_times(2), cs_times(2) - options.us_offset],...
        [axis_z(2), axis_z(2), axis_z(2), axis_z(2)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
        'EdgeAlpha', 0.1);
    fill3(...
        [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
        [cs_times(2) - options.us_offset, cs_times(2), cs_times(2), cs_times(2) - options.us_offset],...
        [axis_z(1), axis_z(1), axis_z(1), axis_z(1)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
   	    'EdgeAlpha', 0.1);
    fill3(...
        [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
        [cs_times(2) - options.us_offset, cs_times(2) - options.us_offset, cs_times(2) - options.us_offset, cs_times(2) - options.us_offset],...
        [axis_z(1), axis_z(2), axis_z(2), axis_z(1)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
        'EdgeAlpha', 0.1);
    fill3(...
        [axis_x(1), axis_x(1), axis_x(2), axis_x(2)],...
        [cs_times(2), cs_times(2), cs_times(2), cs_times(2)],...
        [axis_z(1), axis_z(2), axis_z(2), axis_z(1)],...
        us_color,...
        'FaceAlpha', 0.1,...
        'LineStyle', '-',...
        'EdgeAlpha', 0.1);
end
legend(ribbons);